# Generated by Django 5.1.6 on 2025-05-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'compuser'), (3, 'staff')], default=3),
        ),
    ]
