# Generated by Django 5.1.6 on 2025-05-22 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='resolved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
