# Generated by Django 5.1.6 on 2025-05-26 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_complaints_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
