# Generated by Django 5.1.6 on 2025-06-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0008_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
