# Generated by Django 5.1.6 on 2025-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0009_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='urgency',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10, null=True),
        ),
    ]
